package Images;

public enum ImageName {

    PLACEHOLDER,
    PLACEHOLDER_SMALL,

    //GENERELL IMAGES
    BACKGROUND,
    LOGOUT,
    ARROW_LEFT,
    ARROW_RIGHT,
    GO,

    //STUDENT IMAGES
    STUDENT_WORK,
    STUDENT_PRACTISE,
    STUDENT_PROFILE,

    //LEVEL IMAGES
    LEVEL_EASY,
    LEVEL_MEDIUM,
    LEVEL_HARD,

    //CATEGORY IMAGES
    CATEGORY_CITIES,
    CATEGORY_MOUNTAINS,
    CATEGORY_RIVER,
    CATEGORY_WORLD,

    //BACKGROUND IMAGES
    BACKGROUND_0,
    BACKGROUND_1,
    BACKGROUND_2,
    BACKGROUND_3,
    BACKGROUND_4,
    BACKGROUND_5,
    BACKGROUND_6,
    BACKGROUND_7,
    BACKGROUND_8,
    BACKGROUND_GREEN,
    BACKGROUND_RED,
    BACKGROUND_BROWN,
    BACKGROUD_LILA,

    //AVATAR IMAGES
    AVATAR_LION,
    AVATAR_ZEBRA,
    AVATAR_PENGUIN,
    AVATAR_EAGLE,
    AVATAR_DOLPHIN,
    AVATAR_COALA,
    AVATAR_LION_SMALL,
    AVATAR_ZEBRA_SMALL,
    AVATAR_PENGUIN_SMALL,
    AVATAR_EAGLE_SMALL,
    AVATAR_DOLPHIN_SMALL,
    AVATAR_COALA_SMALL
}
