package Images;

public enum ImageName {

    BACKGROUND,
    LOGOUT,
    AVATAR_LION,
    AVATAR_ZEBRA,
    AVATAR_PENGUIN,
    AVATAR_EAGLE,
    AVATAR_DOLPHIN,
    AVATAR_COALA,
    AVATAR_LION_SMALL,
    AVATAR_ZEBRA_SMALL,
    AVATAR_PENGUIN_SMALL,
    AVATAR_EAGLE_SMALL,
    AVATAR_DOLPHIN_SMALL,
    AVATAR_COALA_SMALL,
    PLACEHOLDER,
    PLACEHOLDER_SMALL
}
