package Main;

public enum Screen
{
    LOGIN,
    MAIN_MENU_STUDENT,
    PROFILE_STUDENT,
    MAIN_MENU_ADMIN,
    CHANGE_PASSWORD_ADMIN,
    CHANGE_PASSWORD_ADMIN_PASSCODE,
    CHANGE_PASSWORD_STUDENT_ADMIN,
    VIEW_STUDENT_PROGRESS_ADMIN,
    VIEW_STUDENT_PROGRESS_CLASS,
    ADMIN_STUDENTS,
    SHOW_STUDENT_PROGRESS,
    SHOW_STUDENT_TEST,
    SHOW_STUDENT_TEST_CLASS,
    CREATE_NEW_TEST,
    PRACTISE_STUDENT,
    WORK_STUDENT,
    PROFILE_SHOW_BACKGROUND,
    PLAYING,
    PRACTISE_STUDENT_GAME_FEEDBACK,
    CREATE_NEW_QUESTION,
    TEST_LIST,
    SHOW_ONE_TEST,
    SHOW_ONE_RECORD,
    SHOW_ONE_TEST_TEMPLATE
}
