package Main;

public enum Screen
{
    LOGIN,
    MAIN_MENU_STUDENT,
    PROFILE_STUDENT,
    MAIN_MENU_ADMIN,
    CHANGE_PASSWORD_ADMIN,
    CHANGE_PASSWORD_ADMIN_PASSCODE,
    CHANGE_PASSWORD_STUDENT_ADMIN,
    VIEW_STUDENT_PROGRESS_ADMIN,
    ADMIN_STUDENTS,
    SHOW_STUDENT_PROGRESS,
    CREATE_NEW_TEST,
    PRACTISE_STUDENT,
    WORK_STUDENT,
    PROFILE_SHOW_BACKGROUND,
    PLAYING,
    PRACTISE_STUDENT_GAME_FEEDBACK
}
