package main;

public enum Screen
{
    LOGIN_STUDENT,
    MAIN_MENU_STUDENT,
    PROFILE_STUDENT,
    MAIN_MENU_ADMIN,
    CHANGE_PASSWORD_ADMIN,
    CHANGE_PASSWORD_ADMIN_PASSCODE,
    CHANGE_PASSWORD_STUDENT_ADMIN,
    VIEW_STUDENT_PROGRESS_ADMIN,
    PRACTISE_STUDENT,
    WORK_STUDENT,
    PROFILE_SHOW_BACKGROUND,
    PLAYING
}
